# Generated by Django 5.2.6 on 2025-09-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_ID',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Melee Weapons', [('onehanded', 'One-Handed'), ('twohanded', 'Two-Handed')]), ('Ranged Weapons', [('bow', 'Bow'), ('crossbow', 'Crossbow')]), ('Armour', [('light', 'Light'), ('medium', 'Medium')]), ('unknown', 'Unknown')], default='unknown', max_length=109),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
