# Generated by Django 5.2.6 on 2025-09-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_category_id_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Melee Weapons', [('onehanded', 'One-Handed Melee'), ('twohanded', 'Two-Handed Melee')]), ('Ranged Weapons', [('bow', 'Bow'), ('crossbow', 'Crossbow')]), ('Armor', [('light', 'Light Armor'), ('medium', 'Medium Armor')]), ('unknown', 'Unknown')], default='unknown', max_length=109),
        ),
    ]
