# Generated by Django 5.2.6 on 2025-09-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Melee Weapons', [('onehanded', 'One-Handed Melee'), ('twohanded', 'Two-Handed Melee')]), ('Ranged Weapons', [('bow', 'Bow'), ('crossbow', 'Crossbow'), ('exotic', 'Exotic')]), ('Armor', [('light', 'Light Armor'), ('medium', 'Medium Armor'), ('heavy', 'Heavy Armor')]), ('unknown', 'Unknown')], default='unknown', max_length=109),
        ),
    ]
