# Generated by Django 5.2.6 on 2025-09-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='product',
            name='review_average',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
