# Generated by Django 5.2.6 on 2025-10-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_review_product_id_alter_review_review_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_score',
            field=models.IntegerField(),
        ),
    ]
