# Generated by Django 5.2.6 on 2025-10-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_cart_item_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_item',
            old_name='product_id',
            new_name='product',
        ),
    ]
