# Generated by Django 5.2.6 on 2025-10-08 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_product_id_cart_item_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='review_average',
            new_name='review',
        ),
    ]
