# Generated by Django 5.2.6 on 2025-10-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_review_average_product_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='review',
            new_name='review_average',
        ),
    ]
