# Generated by Django 5.2.6 on 2025-10-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_review_product_review_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='newProduct', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='newName', max_length=200),
        )
    ]
