# Generated by Django 5.2.6 on 2025-10-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_product_name_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
