# Generated by Django 5.2.6 on 2025-11-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_cart_item_options_wishlist_wishlist_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['user']},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='name',
        ),
    ]
